language: node_js
node_js:
  - stable
branches:
  only:
    - develop
install:
  - npm install
cache:
  directories:
    - node_modules
services: 
-
before_script:
-
script:
  - npm test
after_success:
  - npm run coverage